version: "3.9"

services:
  cosyvoice:
    build:
      context: .                                   # compose is inside the repo
      dockerfile: runtime/python/Dockerfile
    container_name: ${CONTAINER_NAME:-cosyvoice}
    user: "${PUID:-0}:${PGID:-0}"                  # set PUID/PGID in .env to match your TrueNAS dataset owner
    command: ["bash","-lc","python3 ${BOOT_PATH:-runtime/python/boot/boot_cosyvoice.py}"]
    environment:
      MODEL_ID:   ${MODEL_ID:-iic/CosyVoice2-0.5B}
      MODEL_DIR:  ${MODEL_DIR:-/models/CosyVoice2-0.5B}
      TTSFRD_ID:  ${TTSFRD_ID:-iic/CosyVoice-ttsfrd}
      TTSFRD_DIR: ${TTSFRD_DIR:-/models/CosyVoice-ttsfrd}
      HOST:       ${HOST:-0.0.0.0}
      PORT:       ${PORT:-50000}
      MAX_CONC:   ${MAX_CONC:-4}
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-0}   # set empty for CPU-only
    volumes:
      - ${HOST_MODEL_DIR:-/mnt/SSD/Apps/cosyVoice/model}:/models
      - ${HOST_DATA_DIR:-/mnt/SSD/Apps/cosyVoice/data}:/workspace/data
    ports:
      - "${PORT:-50000}:${PORT:-50000}"
    restart: unless-stopped
